name: Vercel Development Deployment
on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  pull-requests: write
  deployments: write
  actions: write
  security-events: write
      
jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.TOKEN }}  
          github-token: ${{ secrets.GITHUB_TOKEN }}  
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} 
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} 